



version: "3.7"

services:
 iris:
  image: intersystems/irishealth:2021.2.0FHIRSQL.197.0
  command: --check-caps false
  ports: ["51773:51773", "1972:1972", "52773:52773", "443:443"]
  volumes: ["./data:/data"]
  environment: [ISC_DATA_DIRECTORY=/data/ifconfig]
  entrypoint: ["/iris-main"]
